"""initial_tables

Revision ID: 5538fd2e1698
Revises: 
Create Date: 2026-03-19 03:15:59.897565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5538fd2e1698'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('STOCK', 'FII', 'CRYPTO', 'FIXED_INCOME', 'CASH', name='assettypeenum'), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'PREMIUM', name='planenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('asset_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_quotes_asset_fetched', 'asset_quotes', ['asset_id', 'fetched_at'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('origin', sa.Enum('MANUAL', 'BINANCE_API', 'B3_API', name='originenum'), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rate_type', sa.Enum('CDI_PERCENTAGE', 'CDI_PLUS', 'PREFIXED', 'IPCA_PLUS', name='ratetypeenum'), nullable=True),
    sa.Column('rate_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('crypto_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stock_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fixed_income_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index('ix_position_history_user_date', 'position_history', ['user_id', 'date'], unique=False)
    op.create_table('wallet_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('BINANCE', 'MERCADO_BITCOIN', 'B3_OAUTH', 'PLUGGY', name='connectiontypeenum'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('api_key_encrypted', sa.String(), nullable=False),
    sa.Column('api_secret_encrypted', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ERROR', 'REVOKED', name='connectionstatusenum'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_connections')
    op.drop_index('ix_position_history_user_date', table_name='position_history')
    op.drop_table('position_history')
    op.drop_table('portfolio_positions')
    op.drop_index('ix_asset_quotes_asset_fetched', table_name='asset_quotes')
    op.drop_table('asset_quotes')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
